
//const prices = [2500, 4500, 1200, 8000, 3200];
//let lowest = prices[0];
//for (let i=1; i < prices.length; i++) { 
//    if (prices[i] < lowest) 
//        {lowest = prices[i]}
//}
//console.log(lowest); is this ok



//const prices = [2500, 4500, 1200, 8000, 3200];
//let total = 0;
//for (let i = 0; i < prices.length; i++) {
//    total = total + prices[i];
//}
//let average = total / prices.length;
//console.log(average);




//const prices = [2500, 4500, 1200, 8000, 3200, 900, 15000];
//let count = 0;
//for(let i = 0; i < prices.length; i++){
//if (prices[i]> 4000){
//    count++;
//}
//}
//console.log(count);


//const numbers = [12, 7, 4, 19, 8, 3, 10, 15,];
//let count=0;
//for(let i=0; i<numbers.length; i++){
//if(numbers[i] % 2 === 1)
//   count++
//}
//console.log(count);


//const numbers = [10, 5, 8, 13, 7, 20, 3, 6];
//let total=0;
//for(let i=0; i<numbers.length; i++){
//if(numbers[i] % 2 === 1)
//    total = total + numbers[i]
//}
//console.log(total);



//const numbers = [12, 5, 22, 7, 30, 9, 18];
//let high = numbers[0];
//for(let i = 0; i < numbers.length; i++){
//    if(numbers[i]%2 ===0)
//        if (numbers[i] > high)
//           high = numbers[i]
//}
//console.log(high);



const prices = [2500, 4500, 1200, 8000, 3200];
const discounts = [500, 1000, 200, 1500, 700];

